-- ============================================================
--  Hospital Management System - Oracle Database Schema
-- ============================================================

-- Sequences
CREATE SEQUENCE DEPT_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PATIENT_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DOCTOR_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE APPT_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE LAB_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MED_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BILL_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;

-- Departments
CREATE TABLE DEPARTMENTS (
    DEPT_ID     NUMBER PRIMARY KEY,
    DEPT_NAME   VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(300),
    CREATED_ON  DATE DEFAULT SYSDATE
);

-- Doctors
CREATE TABLE DOCTORS (
    DOCTOR_ID        NUMBER PRIMARY KEY,
    DOCTOR_CODE      VARCHAR2(20) UNIQUE NOT NULL,
    FIRST_NAME       VARCHAR2(50) NOT NULL,
    LAST_NAME        VARCHAR2(50) NOT NULL,
    GENDER           VARCHAR2(10),
    PHONE            VARCHAR2(15),
    EMAIL            VARCHAR2(100),
    SPECIALIZATION   VARCHAR2(100),
    QUALIFICATION    VARCHAR2(100),
    EXPERIENCE       NUMBER(3),
    DEPT_ID          NUMBER REFERENCES DEPARTMENTS(DEPT_ID),
    CONSULTATION_FEE NUMBER(10,2) DEFAULT 0,
    IS_ACTIVE        NUMBER(1) DEFAULT 1,
    CREATED_ON       DATE DEFAULT SYSDATE
);

-- Patients
CREATE TABLE PATIENTS (
    PATIENT_ID   NUMBER PRIMARY KEY,
    PATIENT_CODE VARCHAR2(20) UNIQUE NOT NULL,
    FIRST_NAME   VARCHAR2(50) NOT NULL,
    LAST_NAME    VARCHAR2(50) NOT NULL,
    GENDER       VARCHAR2(10),
    DOB          DATE,
    BLOOD_GROUP  VARCHAR2(5),
    PHONE        VARCHAR2(15) NOT NULL,
    EMAIL        VARCHAR2(100),
    ADDRESS      VARCHAR2(300),
    CITY         VARCHAR2(50),
    CREATED_ON   DATE DEFAULT SYSDATE
);

-- Appointments
CREATE TABLE APPOINTMENTS (
    APPOINTMENT_ID   NUMBER PRIMARY KEY,
    APPOINTMENT_NO   VARCHAR2(20) UNIQUE NOT NULL,
    PATIENT_ID       NUMBER REFERENCES PATIENTS(PATIENT_ID),
    DOCTOR_ID        NUMBER REFERENCES DOCTORS(DOCTOR_ID),
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME VARCHAR2(10),
    SYMPTOMS         VARCHAR2(500),
    STATUS           VARCHAR2(15) DEFAULT 'SCHEDULED',
    NOTES            VARCHAR2(500),
    CREATED_ON       DATE DEFAULT SYSDATE
);

-- Lab Reports
CREATE TABLE LAB_REPORTS (
    REPORT_ID     NUMBER PRIMARY KEY,
    REPORT_NO     VARCHAR2(20) UNIQUE NOT NULL,
    PATIENT_ID    NUMBER REFERENCES PATIENTS(PATIENT_ID),
    DOCTOR_ID     NUMBER REFERENCES DOCTORS(DOCTOR_ID),
    TEST_NAME     VARCHAR2(100) NOT NULL,
    TEST_CATEGORY VARCHAR2(50),
    TEST_DATE     DATE NOT NULL,
    RESULT        VARCHAR2(500),
    NORMAL_RANGE  VARCHAR2(100),
    UNIT          VARCHAR2(20),
    STATUS        VARCHAR2(15) DEFAULT 'PENDING',
    REMARKS       VARCHAR2(300),
    CHARGES       NUMBER(10,2) DEFAULT 0,
    CREATED_ON    DATE DEFAULT SYSDATE
);

-- Medicines
CREATE TABLE MEDICINES (
    MEDICINE_ID       NUMBER PRIMARY KEY,
    MEDICINE_CODE     VARCHAR2(20) UNIQUE NOT NULL,
    MEDICINE_NAME     VARCHAR2(100) NOT NULL,
    GENERIC_NAME      VARCHAR2(100),
    CATEGORY          VARCHAR2(50),
    MANUFACTURER      VARCHAR2(100),
    UNIT_PRICE        NUMBER(10,2) NOT NULL,
    QUANTITY_IN_STOCK NUMBER DEFAULT 0,
    EXPIRY_DATE       DATE,
    CREATED_ON        DATE DEFAULT SYSDATE
);

-- Bills
CREATE TABLE BILLS (
    BILL_ID            NUMBER PRIMARY KEY,
    BILL_NO            VARCHAR2(20) UNIQUE NOT NULL,
    PATIENT_ID         NUMBER REFERENCES PATIENTS(PATIENT_ID),
    APPOINTMENT_ID     NUMBER REFERENCES APPOINTMENTS(APPOINTMENT_ID),
    CONSULTATION_FEE   NUMBER(10,2) DEFAULT 0,
    LAB_CHARGES        NUMBER(10,2) DEFAULT 0,
    MEDICINE_CHARGES   NUMBER(10,2) DEFAULT 0,
    OTHER_CHARGES      NUMBER(10,2) DEFAULT 0,
    DISCOUNT           NUMBER(10,2) DEFAULT 0,
    TOTAL_AMOUNT       NUMBER(10,2) NOT NULL,
    STATUS             VARCHAR2(10) DEFAULT 'PENDING',
    BILL_DATE          DATE DEFAULT SYSDATE,
    CREATED_ON         DATE DEFAULT SYSDATE
);

-- ============================================================
--  Seed Data
-- ============================================================

INSERT INTO DEPARTMENTS VALUES (DEPT_SEQ.NEXTVAL, 'General Medicine', 'General medical consultations', SYSDATE);
INSERT INTO DEPARTMENTS VALUES (DEPT_SEQ.NEXTVAL, 'Cardiology', 'Heart and cardiovascular diseases', SYSDATE);
INSERT INTO DEPARTMENTS VALUES (DEPT_SEQ.NEXTVAL, 'Neurology', 'Brain and nervous system disorders', SYSDATE);
INSERT INTO DEPARTMENTS VALUES (DEPT_SEQ.NEXTVAL, 'Orthopedics', 'Bone and joint treatments', SYSDATE);
INSERT INTO DEPARTMENTS VALUES (DEPT_SEQ.NEXTVAL, 'Pediatrics', 'Child healthcare', SYSDATE);
INSERT INTO DEPARTMENTS VALUES (DEPT_SEQ.NEXTVAL, 'Pathology / Lab', 'Laboratory and diagnostic services', SYSDATE);
INSERT INTO DEPARTMENTS VALUES (DEPT_SEQ.NEXTVAL, 'Pharmacy', 'Medicines and dispensary', SYSDATE);

INSERT INTO DOCTORS VALUES (DOCTOR_SEQ.NEXTVAL, 'DR-001', 'Rajesh', 'Kumar', 'Male', '9876501001', 'rajesh.k@hospital.com',
    'General Medicine', 'MBBS, MD', 15, 1, 500.00, 1, SYSDATE);
INSERT INTO DOCTORS VALUES (DOCTOR_SEQ.NEXTVAL, 'DR-002', 'Priya', 'Sharma', 'Female', '9876501002', 'priya.s@hospital.com',
    'Cardiology', 'MBBS, MD, DM', 12, 2, 800.00, 1, SYSDATE);
INSERT INTO DOCTORS VALUES (DOCTOR_SEQ.NEXTVAL, 'DR-003', 'Venkat', 'Rao', 'Male', '9876501003', 'venkat.r@hospital.com',
    'Neurology', 'MBBS, MD, DM', 10, 3, 700.00, 1, SYSDATE);
INSERT INTO DOCTORS VALUES (DOCTOR_SEQ.NEXTVAL, 'DR-004', 'Anitha', 'Reddy', 'Female', '9876501004', 'anitha.r@hospital.com',
    'Orthopedics', 'MBBS, MS', 8, 4, 600.00, 1, SYSDATE);

INSERT INTO MEDICINES VALUES (MED_SEQ.NEXTVAL, 'MED-001', 'Paracetamol', 'Acetaminophen', 'Analgesic', 'Cipla', 2.50, 500, TO_DATE('2026-12-31','YYYY-MM-DD'), SYSDATE);
INSERT INTO MEDICINES VALUES (MED_SEQ.NEXTVAL, 'MED-002', 'Amoxicillin', 'Amoxicillin', 'Antibiotic', 'Sun Pharma', 8.00, 300, TO_DATE('2026-06-30','YYYY-MM-DD'), SYSDATE);
INSERT INTO MEDICINES VALUES (MED_SEQ.NEXTVAL, 'MED-003', 'Metformin', 'Metformin HCl', 'Antidiabetic', 'Dr Reddys', 5.50, 400, TO_DATE('2026-09-30','YYYY-MM-DD'), SYSDATE);
INSERT INTO MEDICINES VALUES (MED_SEQ.NEXTVAL, 'MED-004', 'Atorvastatin', 'Atorvastatin Calcium', 'Statin', 'Lupin', 12.00, 250, TO_DATE('2026-11-30','YYYY-MM-DD'), SYSDATE);
INSERT INTO MEDICINES VALUES (MED_SEQ.NEXTVAL, 'MED-005', 'Omeprazole', 'Omeprazole', 'Antacid', 'Torrent', 4.50, 350, TO_DATE('2026-08-31','YYYY-MM-DD'), SYSDATE);

COMMIT;
